main: ce.ajneb97.ConditionalEvents
version: 3.16.1
name: ConditionalEvents
api-version: 1.13
softdepend: [PlaceholderAPI]
author: Ajneb97

commands:
  ce:
    description: Main command of ConditionalEvents
    aliases: conditionalevents