main: ce.ajneb97.ConditionalEvents
version: 4.20.1
name: ConditionalEvents
api-version: 1.13
softdepend: [PlaceholderAPI,Citizens,WorldGuardEvents,WorldGuard]
author: Ajneb97

commands:
  conditionalevents:
    description: Main command of ConditionalEvents
    aliases: ce