package ce.ajneb97.eventos;

public enum TipoEvento {

	PLAYER_RESPAWN,
	PLAYER_DEATH,
	BLOCK_INTERACT,
	ITEM_INTERACT,
	PLAYER_ATTACK,
	PLAYER_KILL,
	PLAYER_DAMAGE,
	BLOCK_BREAK,
	BLOCK_PLACE,
	PLAYER_COMMAND,
	PLAYER_CHAT,
	ITEM_CONSUME,
	ITEM_PICKUP,
	ITEM_CRAFT,
	PLAYER_JOIN,
	PLAYER_LEAVE,
	PLAYER_LEVELUP,
	PLAYER_WORLD_CHANGE,
	PLAYER_ARMOR,
	ITEM_DROP,
	ITEM_MOVE,
	ITEM_SELECT,
	REPETITIVE,
	REPETITIVE_SERVER,
	ENTITY_SPAWN,
	ENTITY_INTERACT,
	CONSOLE_COMMAND,
	CUSTOM
}
